-- Tabela de Transações
create table transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  description text not null,
  amount numeric not null,
  type text not null, -- 'income' or 'expense'
  category text not null,
  context text default 'individual', -- 'individual' or 'family'
  owner text,
  date date not null
);

-- Tabela de Metas
create table goals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  description text not null,
  target_amount numeric not null,
  current_amount numeric default 0,
  deadline date,
  context text default 'individual'
);

-- Tabela de Usuários (Opcional, para autocomplete)
create table app_users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null
);

-- Políticas de Segurança (Simples para começar - permitir tudo anonimamente)
-- Em produção, você deve configurar RLS (Row Level Security) e Auth.
alter table transactions enable row level security;
create policy "Enable all access for all users" on transactions for all using (true) with check (true);

alter table goals enable row level security;
create policy "Enable all access for all users" on goals for all using (true) with check (true);

alter table app_users enable row level security;
create policy "Enable all access for all users" on app_users for all using (true) with check (true);
